export * from "./uploadResult1"
export * from "./dashboard"
export * from "./remark"
export * from "./students"
export * from "./uploadResult"
export * from "./timetable"
export * from "./scheme"
export * from "./loginTeacher"
