export const data = [
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
]

export const classData = [
  { "S/N": "001", Classes: "JSS 1", empty: ":" },
  { "S/N": "002", Classes: "JSS 2", empty: ":" },
  { "S/N": "003", Classes: "JSS 3", empty: ":" },
  { "S/N": "004", Classes: "SSS 1", empty: ":" },
  { "S/N": "005", Classes: "SSS 2", empty: ":" },
  { "S/N": "006", Classes: "SSS 3", empty: ":" },
]

export const subjectsData = [
  { "S/N": "001", Subjects: "English", empty: ":" },
  { "S/N": "002", Subjects: "Mathematics", empty: ":" },
  { "S/N": "003", Subjects: "Biology", empty: ":" },
  { "S/N": "004", Subjects: "Physics", empty: ":" },
  { "S/N": "005", Subjects: "Chemistry", empty: ":" },
  { "S/N": "006", Subjects: "Geography", empty: ":" },
  { "S/N": "007", Subjects: "Agriculture", empty: ":" },
  { "S/N": "008", Subjects: "Igbo language", empty: ":" },
  { "S/N": "009", Subjects: "CRS", empty: ":" },
  { "S/N": "010", Subjects: "Civic Education", empty: ":" },
  { "S/N": "011", Subjects: "Computer Science", empty: ":" },
  { "S/N": "012", Subjects: "Health Science", empty: ":" },
]

export const eventsData = [
  {
    "S/N": "001",
    Activity: "Mid-Term Break",
    "Start Date": "15-10-2025",
    "End Date": "23-10-2025",
    Description:
      "All student are to resume to school on the 23rd of October 2025.",
  },
  {
    "S/N": "002",
    Activity: "Examinations",
    "Start Date": "15-10-2025",
    "End Date": "23-10-2025",
    Description: "All student will start and finish exams the same date.",
  },
  {
    "S/N": "003",
    Activity: "Mid-Term Break",
    "Start Date": "15-10-2025",
    "End Date": "23-10-2025",
    Description:
      "All student are to resume to school on the 23rd of October 2025.",
  },
  {
    "S/N": "004",
    Activity: "Examinations",
    "Start Date": "15-10-2025",
    "End Date": "23-10-2025",
    Description: "All student will start and finish exams the same date.",
  },
  {
    "S/N": "005",
    Activity: "Send-Off Party",
    "Start Date": "15-10-2025",
    "End Date": "N/A",
    Description: "There will be a send-off party for our out-going students.",
  },
  {
    "S/N": "006",
    Activity: "Resumption",
    "Start Date": "15-10-2025",
    "End Date": "N/A",
    Description:
      "All student are to resume to school on the 23rd of October 2025.",
  },
]

export const resultsData = [
  {
    "S/N": "001",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "English",
  },
  {
    "S/N": "002",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Mathematics",
  },
  {
    "S/N": "003",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Biology",
  },
  {
    "S/N": "004",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Physics",
  },
  {
    "S/N": "005",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Chemistry",
  },
  {
    "S/N": "006",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Geography",
  },
  {
    "S/N": "007",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Agriculture",
  },
  {
    "S/N": "008",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Igbo language",
  },
  {
    "S/N": "009",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "CRS",
  },
  {
    "S/N": "010",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Civic Education",
  },
  {
    "S/N": "011",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Computer Science",
  },
  {
    "S/N": "012",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Health Science",
  },
]

export const subjectResultsData = [
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
  {
    "s/n": "001",
    student: "Udeh Desire",
    assessment: "2",
    exam: "25",
    total: "31",
    grade: "F",
  },
]

export const paymentsData = [
  {
    "S/N": "001",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "002",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "003",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "004",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "005",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "006",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "007",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "008",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "009",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "010",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "011",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "012",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "013",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "014",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "015",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
]

export const paymentBreakdownData = [
  {
    "S/N": "001",
    Item: "Tuition",
    Amount: "₦30,000.00",
    Description: "Only for boarders",
  },
  {
    "S/N": "002",
    Item: "Boarding",
    Amount: "₦25,000.00",
    Description: "Applicable to JSS1 & SS1 students",
  },
  {
    "S/N": "003",
    Item: "Text Books Deposit",
    Amount: "₦15,000.00",
    Description: "All students",
  },
  {
    "S/N": "004",
    Item: "Exercise Books",
    Amount: "₦5,000.00",
    Description: "All students (Per session)",
  },
  {
    "S/N": "005",
    Item: "Prospectus",
    Amount: "₦1,000.00",
    Description: "All students",
  },
  {
    "S/N": "006",
    Item: "ID Card",
    Amount: "₦1,000.00",
    Description: "New students",
  },
  {
    "S/N": "007",
    Item: "Stationery",
    Amount: "₦1,000.00",
    Description: "All students",
  },
  {
    "S/N": "008",
    Item: "Clubs and Societies",
    Amount: "₦1,000.00",
    Description: "All students",
  },
  {
    "S/N": "009",
    Item: "Sports",
    Amount: "₦1,000.00",
    Description: "All students",
  },
  {
    "S/N": "010",
    Item: "Medical",
    Amount: "₦30,000.00",
    Description: "All students",
  },
  {
    "S/N": "011",
    Item: "Vocational",
    Amount: "₦1,000.00",
    Description: "₦2,000.00",
  },
  {
    "S/N": "012",
    Item: "Utilities",
    Amount: "₦2,000.00",
    Description: "All student",
  },
]

const attendance = {
  "Week 1": {
    mon: "Present",
    tue: "Present",
    wed: "Absent",
    thur: "Present",
    fri: "Absent",
    sat: "",
    sun: "",
  },
}

export const attendanceData = [
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
  {
    name: "Ene Maria Chidimma",
    attendance: attendance,
  },
]

export const studentsAttendance = [
  {
    weeks: "Week 1",
    mon: "Present",
    tue: "Present",
    wed: "Absent",
    thur: "Present",
    fri: "Absent",
    sat: "",
    sun: "",
  },
  {
    weeks: "Week 2",
    mon: "Present",
    tue: "Absent",
    wed: "Absent",
    thur: "Present",
    fri: "Absent",
    sat: "",
    sun: "",
  },
  {
    weeks: "Week 3",
    mon: "Present",
    tue: "Present",
    wed: "Absent",
    thur: "Present",
    fri: "Absent",
    sat: "",
    sun: "",
  },
  {
    weeks: "Week 4",
    mon: "Present",
    tue: "Present",
    wed: "Absent",
    thur: "Present",
    fri: "Absent",
    sat: "",
    sun: "",
  },
  {
    weeks: "Week 5",
    mon: "Present",
    tue: "Present",
    wed: "Absent",
    thur: "Present",
    fri: "Absent",
    sat: "",
    sun: "",
  },
  {
    weeks: "Week 6",
    mon: "Present",
    tue: "Present",
    wed: "Absent",
    thur: "Present",
    fri: "Absent",
    sat: "",
    sun: "",
  },
  {
    weeks: "Week 7",
    mon: "Present",
    tue: "Present",
    wed: "Absent",
    thur: "Present",
    fri: "Absent",
    sat: "",
    sun: "",
  },
]
