export const data = [
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
  {
    regNo: "001",
    surname: "Udeh",
    firstName: "Desire",
    otherName: "Chiamaka",
    gender: "Female",
    class: "SSS1A",
    regDate: "20-09-2024",
  },
]

export const classData = [
  { "s/n": "001", classes: "JSS 1", empty: ":" },
  { "s/n": "002", classes: "JSS 2", empty: ":" },
  { "s/n": "003", classes: "JSS 3", empty: ":" },
  { "s/n": "004", classes: "SSS 1", empty: ":" },
  { "s/n": "005", classes: "SSS 2", empty: ":" },
  { "s/n": "006", classes: "SSS 3", empty: ":" },
]

export const subjectsData = [
  { "S/N": "001", Subjects: "English", "": ":" },
  { "S/N": "002", Subjects: "Mathematics", "": ":" },
  { "S/N": "003", Subjects: "Biology", "": ":" },
  { "S/N": "004", Subjects: "Physics", "": ":" },
  { "S/N": "005", Subjects: "Chemistry", "": ":" },
  { "S/N": "006", Subjects: "Geography", "": ":" },
  { "S/N": "007", Subjects: "Agriculture", "": ":" },
  { "S/N": "008", Subjects: "Igbo language", "": ":" },
  { "S/N": "009", Subjects: "CRS", "": ":" },
  { "S/N": "010", Subjects: "Civic Education", "": ":" },
  { "S/N": "011", Subjects: "Computer Science", "": ":" },
  { "S/N": "012", Subjects: "Health Science", "": ":" },
]

export const eventsData = [
  {
    "S/N": "001",
    Activity: "Mid-Term Break",
    "Start Date": "15-10-2025",
    "End Date": "23-10-2025",
    Description:
      "All student are to resume to school on the 23rd of October 2025.",
  },
  {
    "S/N": "002",
    Activity: "Examinations",
    "Start Date": "15-10-2025",
    "End Date": "23-10-2025",
    Description: "All student will start and finish exams the same date.",
  },
  {
    "S/N": "003",
    Activity: "Mid-Term Break",
    "Start Date": "15-10-2025",
    "End Date": "23-10-2025",
    Description:
      "All student are to resume to school on the 23rd of October 2025.",
  },
  {
    "S/N": "004",
    Activity: "Examinations",
    "Start Date": "15-10-2025",
    "End Date": "23-10-2025",
    Description: "All student will start and finish exams the same date.",
  },
  {
    "S/N": "005",
    Activity: "Send-Off Party",
    "Start Date": "15-10-2025",
    "End Date": "N/A",
    Description: "There will be a send-off party for our out-going students.",
  },
  {
    "S/N": "006",
    Activity: "Resumption",
    "Start Date": "15-10-2025",
    "End Date": "N/A",
    Description:
      "All student are to resume to school on the 23rd of October 2025.",
  },
]

export const resultsData = [
  {
    "S/N": "001",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "English",
  },
  {
    "S/N": "002",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Mathematics",
  },
  {
    "S/N": "003",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Biology",
  },
  {
    "S/N": "004",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Physics",
  },
  {
    "S/N": "005",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Chemistry",
  },
  {
    "S/N": "006",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Geography",
  },
  {
    "S/N": "007",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Agriculture",
  },
  {
    "S/N": "008",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Igbo language",
  },
  {
    "S/N": "009",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "CRS",
  },
  {
    "S/N": "010",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Civic Education",
  },
  {
    "S/N": "011",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Computer Science",
  },
  {
    "S/N": "012",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1A",
    Subjects: "Health Science",
  },
]

export const paymentsData = [
  {
    "S/N": "001",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "002",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "003",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "004",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "005",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "006",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "007",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "008",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "009",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "010",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "011",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "012",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "013",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
  {
    "S/N": "014",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Paid",
  },
  {
    "S/N": "015",
    Surname: "Udeh",
    FirstName: "Desire",
    OtherName: "Chiamaka",
    Gender: "Female",
    Class: "SSS1 A",
    Status: "Unpaid",
  },
]

export const paymentBreakdownData = [
  {
    "S/N": "001",
    Item: "Tuition",
    Amount: "₦30,000.00",
    Description: "Only for boarders",
  },
  {
    "S/N": "002",
    Item: "Boarding",
    Amount: "₦25,000.00",
    Description: "Applicable to JSS1 & SS1 students",
  },
  {
    "S/N": "003",
    Item: "Text Books Deposit",
    Amount: "₦15,000.00",
    Description: "All students",
  },
  {
    "S/N": "004",
    Item: "Exercise Books",
    Amount: "₦5,000.00",
    Description: "All students (Per session)",
  },
  {
    "S/N": "005",
    Item: "Prospectus",
    Amount: "₦1,000.00",
    Description: "All students",
  },
  {
    "S/N": "006",
    Item: "ID Card",
    Amount: "₦1,000.00",
    Description: "New students",
  },
  {
    "S/N": "007",
    Item: "Stationery",
    Amount: "₦1,000.00",
    Description: "All students",
  },
  {
    "S/N": "008",
    Item: "Clubs and Societies",
    Amount: "₦1,000.00",
    Description: "All students",
  },
  {
    "S/N": "009",
    Item: "Sports",
    Amount: "₦1,000.00",
    Description: "All students",
  },
  {
    "S/N": "010",
    Item: "Medical",
    Amount: "₦30,000.00",
    Description: "All students",
  },
  {
    "S/N": "011",
    Item: "Vocational",
    Amount: "₦1,000.00",
    Description: "₦2,000.00",
  },
  {
    "S/N": "012",
    Item: "Utilities",
    Amount: "₦2,000.00",
    Description: "All student",
  },
]
